### ISSUE TITLE
add-on plan "mongolab:sandbox" not available on Heroku anymore

### ISSUE THREAD

**Issue by CicheR** [slackapi/template-triage-bot#25]
When trying to deploy the app to Heroku using `app.json` (following the instructions in `docs/DEPLOY_Heroku.md`), the following error is given:
- **Couldn't find either the add-on service or the add-on plan of "mongolab:sandbox".**

![image](https://user-images.githubusercontent.com/46723276/144178083-18ff52e1-0630-4b27-adc8-888fe4462980.png)

**Comment by marks** [comment]
@CicheR - I would recommend looking into MongoDB's own hosting at https://www.mongodb.com/atlas/database which has a free tier. I'll try to update the Heroku setup instructions too

**Comment by marks** [comment]
Hey @CicheR & @liangjacky (I saw you +1'ed Ciche's issue post), you can see my new branch here https://github.com/marks/template-triage-bot/tree/marks-update-heroku-docs that has an updated [app.json](https://github.com/marks/template-triage-bot/blob/marks-update-heroku-docs/app.json) and [DEPLOY_Heroku.md](https://github.com/marks/template-triage-bot/blob/marks-update-heroku-docs/docs/DEPLOY_Heroku.md) file if you'd like.

🗒️ Note - that "Deploy to Heroku" button will use the @slackapi version of the code. You can go directly to https://heroku.com/deploy?template=https://github.com/marks/template-triage-bot/tree/marks-update-heroku-docs if you want to use this updated branch.

I plan to submit a PR to @slackapi's repo once my other PR, #30, is accepted. Sorry about the hassle. I miss that free MongoDB Heroku add on too.

**Comment by seratch** [comment]
Fixed by #31
